language: cpp

sudo: true

dist: xenial

compiler:
        - gcc
        - clang

stages:
        - smoke-test
        #- main-test
        #- extended-test

matrix:
        include:
                ## Xenial/GCC
                # Smoke tests
                - env:
                        - TARGET=smoke
                        - TABLE=1
                        - PAPER=0
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=2
                        - PAPER=0
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=3
                        - PAPER=0
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=4
                        - PAPER=0
                  stage: smoke-test
                # Main tests
                #- env:
                #        - TARGET=main
                #        - TABLE=1
                #  stage: main-test
                #- env:
                #        - TARGET=main
                #        - TABLE=2
                #  stage: main-test
                #- env:
                #        - TARGET=main
                #        - TABLE=3
                #  stage: main-test
                #- env:
                #        - TARGET=main
                #        - TABLE=4
                #  stage: main-test
                # Extended tests
                #- env:
                #        - TARGET=extended
                #        - TABLE=1
                #  stage: extended-test
                #- env:
                #        - TARGET=extended
                #        - TABLE=2
                #  stage: extended-test
                #- env:
                #        - TARGET=extended
                #        - TABLE=3
                #  stage: extended-test
                #- env:
                #        - TARGET=extended
                #        - TABLE=4
                #  stage: extended-test
        global:
                - TARGET=smoke
        matrix:
                - TABLE=1 PAPER=0
                - TABLE=2 PAPER=0
                - TABLE=3 PAPER=0
                - TABLE=4 PAPER=0
                - TABLE=1 PAPER=1
                - TABLE=2 PAPER=1
                - TABLE=3 PAPER=1
                - TABLE=4 PAPER=1
        allow_failures:
                - env: TABLE=1 PAPER=1
                - env: TABLE=2 PAPER=1
                - env: TABLE=3 PAPER=1
                - env: TABLE=4 PAPER=1

before_install:
        - sudo apt-get -y update
        - sudo apt-get -y install build-essential

install:
        - make

script:
        - travis_wait ./travis/travis_${TARGET}_test.sh ${TABLE} ${PAPER}
