language: cpp

sudo: true

dist: xenial

compiler:
        - gcc
        - clang

stages:
        - smoke-test

matrix:
        include:
                ## Xenial/GCC
                # Smoke tests
                - env:
                        - TARGET=smoke
                        - TABLE=1
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=2
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=3
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=4
                  stage: smoke-test
                # Main tests
                - env:
                        - TARGET=main
                        - TABLE=1
                  stage: main-test
                - env:
                        - TARGET=main
                        - TABLE=2
                  stage: main-test
                - env:
                        - TARGET=main
                        - TABLE=3
                  stage: main-test
                - env:
                        - TARGET=main
                        - TABLE=4
                  stage: main-test

before_install:
        - sudo apt-get -y update
        - sudo apt-get -y install build-essential

install:
        - make

script:
        - ./travis/travis_${TARGET}_test.sh ${TABLE}
