language: cpp

sudo: true

dist: xenial

stages:
        - smoke-test

matrix:
        include:
                - env:
                        - TARGET=smoke
                        - TABLE=1
                  stage: smoke-test
                - env:
                        - TARGET=smoke
                        - TABLE=2
                  stage: smoke-test

before_install:
        - sudo apt-get -y update
        - sudo apt-get -y install build-essential

install:
        - make

script:
        - ./travis/travis_${TARGET}_test.sh ${TABLE}
